const links = [
  {
    name: "Custom URL",
    URL: "https://",
    userFaceURL: "example.com",
    prefix: "https://",
    placeholder: "example.com",
    enter: "Custom URL",
  },
  {
    name: "Instagram",
    URL: "https://instagram.com/",
    userFaceURL: "@username",
    prefix: "@",
    placeholder: "username",
    enter: "Instagram Username",
  },
  {
    name: "LinkTree",
    URL: "https://linktr.ee/",
    userFaceURL: "linktr.ee/",
    prefix: "linktr.ee/",
    placeholder: "username",
    enter: "LinkTree URL",
  },
  {
    name: "Snapchat",
    URL: "https://snapchat.com/add/",
    userFaceURL: "@username",
    prefix: "@",
    placeholder: "username",
    enter: "Snapchat Username",
  },
  {
    name: "TikTok",
    URL: "https://tiktok.com/@",
    userFaceURL: "@username",
    prefix: "@",
    placeholder: "username",
    enter: "TikTok Username",
  },
  {
    name: "Venmo",
    URL: "https://venmo.com/",
    userFaceURL: "@username",
    prefix: "@",
    placeholder: "username",
    enter: "Venmo Username",
  },
  {
    name: "Twitter",
    URL: "https://twitter.com/",
    userFaceURL: "@username",
    prefix: "@",
    placeholder: "username",
    enter: "Twitter Username",
  },
  {
    name: "Youtube",
    URL: "https://youtube.com/",
    userFaceURL: "youtube.com/",
    prefix: "youtube.com/",
    placeholder: "url",
    enter: "Youtube URL",
  },
  {
    name: "Facebook",
    URL: "https://facebook.com/",
    userFaceURL: "facebook.com/",
    prefix: "facebook.com/",
    placeholder: "url",
    enter: "Facebook URL",
  },
  {
    name: "Spotify",
    URL: "https://spotify.com/",
    userFaceURL: "spotify.com/",
    prefix: "spotify.com/",
    placeholder: "songurl",
    enter: "Spotify URL",
  },
  {
    name: "Apple Music",
    URL: "https://music.apple.com/",
    userFaceURL: "music.apple.com/",
    prefix: "music.apple.com/",
    placeholder: "songurl",
    enter: "Apple Music URL",
  },
];

export default links;
